### ISSUE TITLE
Logical issue while using 2 instance of schema-form

### ISSUE THREAD

**Issue by karan3112** [fightingm/vue-awesome-form#2]
I have a senario where I have to use multiple instances of the schema-form on same page with same schema. But even after using different `:key` both are using the same value. I have 2 seperate value variables still somehow I'm facing this issue. 

As in if I update the value of a field `name` in `form1` the value of `name` in `form2` is also updated.

**Comment by fightingm** [comment]
update 'vue-awesome-form' to v1.0.4 and try again.
