### ISSUE TITLE
Alternative output model format

### ISSUE THREAD

**Issue by shreyasnagare** [fightingm/vue-awesome-form#5]
I think the schema format is amazing since it preserves the nested hierarchy properly. However, this hierarchy is lost once I get the data back as just key-value pairs. Is there a way to get all the values in the same structure as the schema?

For example: 
## schema
```js
"location": {
    "type": "TheTree",
    "title": "地址信息",
    "propertyOrder": 3,
    "properties": {
        "province": {
            "type": "TheInput",
            "title": "省份",
            "rules": {
                "required": true,
                "message": "The 省份 cannot be empty"
            }
        },
        "city": {
            "type": "TheInput",
            "title": "市",
            "rules": {
                "required": true,
                "message": "The 市 cannot be empty"
            }
        }
    }
}
```
## output
```js
"location": {
    "title": "地址信息",
    "value": {
        "province": {
            "title": "省份",
            "value": "北京省"
        },
        "city": {
            "title": "市",
            "value": "北京市"
        }
    }
}
```

This will help us in preserving the hierarchy of the data.

P.S.: Thank you for creating this project. It's one of a kind and pretty useful.

**Comment by shreyasnagare** [comment]
My bad. Got it!

**Comment by MUMUKSHMEGHWAL** [comment]
@shreyasnagare hey, I am using this form but getting *[Vue warn]: Error in render: "TypeError: Cannot convert undefined or null to object"*.

can you help?
